[ ca ]
default_ca = myCA

[ myCA ]
dir = /home/jry/lab1/myCA
crl_dir = $dir/conf
database = $dir/index
new_certs_dir = $dir/newcerts

certificate = $dir/cacert.pem
serial = $dir/serial
private_key = $dir/private/cakey.pem
crlnumber = $dir/crlnumber
RANDFILE = $dir/private/.rand

default_days = 365
default_crl_days = 30
default_md = md5
unique_subject = no

policy = policy_any

[ policy_any ]
stateOrProvinceName = optional
localityName = optional
organizationName = optional
organizationalUnitName = optional
commonName = supplied
emailAddress = optional
